FROM mysql

MAINTAINER ljinke, ljinke@gmail.com

ADD ./my.cnf /etc/mysql/my.cnf
ENV MYSQL_ROOT_PASSWORD ms_pwd_2015
ENV MYSQL_DATABASE jasperserver_pro55
ENV MYSQL_USER jasper
ENV MYSQL_PASSWORD 4321vela
